services:
  mercure:
    container_name: mercure
    hostname: mercure
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      MERCURE_PUBLISHER_JWT_KEY: 'tajne'
      MERCURE_SUBSCRIBER_JWT_KEY: 'tajne'
      SERVER_NAME: ':80'
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    ports:
      - 8888:80
    volumes:
      - mercure_data:/data
      - mercure_config:/config
  db:
    container_name: db
    hostname: db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: chat
      MYSQL_DATABASE: chat
      MYSQL_USER: chat
      MYSQL_PASSWORD: chat
    ports:
      - 2400:3306
    volumes:
      - db_data:/var/lib/mysql
  redis:
    container_name: redis
    hostname: redis
    image: "redis:alpine"
    restart: unless-stopped
    command: redis-server
    ports:
      - 5500:6379
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
volumes:
  mercure_data:
  mercure_config:
  db_data:
  redis-data:
  redis-conf: